openapi: 3.0.0
info:
  title: Swagger Petstore
  version: 1.0.0
servers:
  - url: https://petstore.swagger.io/v2
paths:
  /pet:
    post:
      summary: Add a new pet to the store
      description: Add a new pet with a name, category, and status.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - status
              properties:
                id:
                  type: integer
                  example: 123
                name:
                  type: string
                  example: "Fluffy"
                category:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Dogs"
                status:
                  type: string
                  enum: [available, pending, sold]
                  example: available
      responses:
        '200':
          description: Pet added successfully
        '405':
          description: Invalid input
    put:
      summary: Update an existing pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: integer
                  example: 123
                name:
                  type: string
                  example: "Fluffy Updated"
                status:
                  type: string
                  enum: [available, pending, sold]
                  example: pending
      responses:
        '200':
          description: Pet updated successfully
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
