openapi: 3.0.3
info:
  title: ToDo API
  description: A simple API for managing your to-do list.
  version: 1.0.0
servers:
  - url: https://api.example.com/v2
    description: Production server
  - url: http://localhost:3000
    description: Local development server

paths:
  /todos:
    get:
      summary: List all to-do items
      operationId: listTodos
      tags:
        - ToDos
      responses:
        '200':
          description: A list of to-do items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new to-do item
      operationId: createTodo
      tags:
        - ToDos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: To-do item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /todos/{id}:
    get:
      summary: Get a specific to-do item
      operationId: getTodo
      tags:
        - ToDos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single to-do item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: To-do item not found

    delete:
      summary: Delete a to-do item
      operationId: deleteTodo
      tags:
        - ToDos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Item deleted successfully

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false

    NewTodo:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
